// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// AiderAdapter handles Aider CLI tool configuration.
// Aider uses .aider.conf.yml for configuration.
// https://aider.chat/
type AiderAdapter struct{}

// Name returns the adapter name
func (a *AiderAdapter) Name() string {
	return "Aider"
}

// Detect checks if this is an Aider project.
// Look for .aider.conf.yml or .aider/ folder.
func (a *AiderAdapter) Detect(projectPath string) bool {
	confFile := filepath.Join(projectPath, ".aider.conf.yml")
	if _, err := os.Stat(confFile); err == nil {
		return true
	}
	aiderDir := filepath.Join(projectPath, ".aider")
	if info, err := os.Stat(aiderDir); err == nil && info.IsDir() {
		return true
	}
	return false
}

// Install creates Aider configuration from templates.
func (a *AiderAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	confFile := filepath.Join(opts.TargetDir, ".aider.conf.yml")
	contextFile := filepath.Join(opts.TargetDir, ".aider-context.md")

	if _, err := os.Stat(confFile); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("aider config %s already exists (use --force to overwrite)", confFile)
	}

	if opts.DryRun {
		return nil
	}

	// Create .aider.conf.yml
	confContent := a.buildConfigContent()
	if err := os.WriteFile(confFile, []byte(confContent), 0644); err != nil {
		return err
	}

	// Create .aider-context.md
	contextContent := a.buildContextContent(tmpl)
	return os.WriteFile(contextFile, []byte(contextContent), 0644)
}

// buildConfigContent creates .aider.conf.yml
func (a *AiderAdapter) buildConfigContent() string {
	return `# Aider Configuration - Generated by AGEN
# https://aider.chat/docs/config.html

# Model settings
# model: gpt-4
# edit-format: diff

# Git settings
auto-commits: true
dirty-commits: false

# Context
read:
  - .aider-context.md

# Behavior
watch-files: true
auto-lint: true
`
}

// buildContextContent creates the .aider-context.md file
func (a *AiderAdapter) buildContextContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Aider Context - Generated by AGEN\n\n")
	sb.WriteString("> This file provides context for Aider.\n")
	sb.WriteString("> Generated by AGEN (https://github.com/eshanized/agen)\n\n")
	sb.WriteString("---\n\n")

	// Code standards
	sb.WriteString("## Project Standards\n\n")
	sb.WriteString("- Follow clean code principles (SRP, DRY, KISS)\n")
	sb.WriteString("- Use meaningful names that reveal intent\n")
	sb.WriteString("- Keep functions small and focused\n")
	sb.WriteString("- Write tests for new functionality\n")
	sb.WriteString("- Document public APIs\n\n")

	// Agents
	sb.WriteString("## Available Modes\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills
	sb.WriteString("## Skills\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows
	sb.WriteString("## Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// Update updates Aider configuration
func (a *AiderAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	contextFile := filepath.Join(opts.TargetDir, ".aider-context.md")

	if _, err := os.Stat(contextFile); os.IsNotExist(err) {
		if err := a.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".aider.conf.yml", ".aider-context.md")
	} else {
		if opts.Force || opts.DryRun {
			contextContent := a.buildContextContent(tmpl)
			if !opts.DryRun {
				if err := os.WriteFile(contextFile, []byte(contextContent), 0644); err != nil {
					return nil, err
				}
			}
			changes.Updated = append(changes.Updated, ".aider-context.md")
		} else {
			changes.Skipped = append(changes.Skipped, ".aider-context.md")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the context file
func (a *AiderAdapter) GetRulesPath() string {
	return ".aider-context.md"
}
