// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// ClineAdapter handles Cline (formerly Roo-Cline) extension for VS Code.
// Cline uses .clinerules file in the project root.
// https://github.com/cline/cline
type ClineAdapter struct{}

// Name returns the adapter name
func (c *ClineAdapter) Name() string {
	return "Cline"
}

// Detect checks if this is a Cline project.
// Look for .clinerules or .cline/ folder.
func (c *ClineAdapter) Detect(projectPath string) bool {
	rulesFile := filepath.Join(projectPath, ".clinerules")
	if _, err := os.Stat(rulesFile); err == nil {
		return true
	}
	clineDir := filepath.Join(projectPath, ".cline")
	if info, err := os.Stat(clineDir); err == nil && info.IsDir() {
		return true
	}
	return false
}

// Install creates Cline configuration from templates.
func (c *ClineAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	rulesFile := filepath.Join(opts.TargetDir, ".clinerules")

	if _, err := os.Stat(rulesFile); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("cline rules file %s already exists (use --force to overwrite)", rulesFile)
	}

	content := c.buildRulesContent(tmpl)

	if opts.DryRun {
		return nil
	}

	return os.WriteFile(rulesFile, []byte(content), 0644)
}

// buildRulesContent creates the .clinerules content
func (c *ClineAdapter) buildRulesContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Cline Rules - Generated by AGEN\n\n")
	sb.WriteString("> This file was generated by AGEN (AI Agent Template Manager)\n")
	sb.WriteString("> https://github.com/eshanized/agen\n\n")
	sb.WriteString("---\n\n")

	// Global rules
	sb.WriteString("## Project Rules\n\n")
	sb.WriteString("### Code Quality\n")
	sb.WriteString("- Follow clean code principles (SRP, DRY, KISS)\n")
	sb.WriteString("- Use meaningful, descriptive names\n")
	sb.WriteString("- Keep functions small (max 20 lines)\n")
	sb.WriteString("- Write comprehensive tests\n\n")

	sb.WriteString("### Safety\n")
	sb.WriteString("- Always ask before making destructive changes\n")
	sb.WriteString("- Verify file paths before operations\n")
	sb.WriteString("- Create backups when modifying existing files\n\n")

	// Agents
	sb.WriteString("## Available Modes\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills summary
	sb.WriteString("## Skills Reference\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows
	sb.WriteString("## Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// Update updates Cline configuration
func (c *ClineAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	rulesFile := filepath.Join(opts.TargetDir, ".clinerules")

	if _, err := os.Stat(rulesFile); os.IsNotExist(err) {
		if err := c.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".clinerules")
	} else {
		if opts.Force || opts.DryRun {
			if err := c.Install(tmpl, InstallOptions{
				TargetDir: opts.TargetDir,
				DryRun:    opts.DryRun,
				Force:     true,
			}); err != nil {
				return nil, err
			}
			changes.Updated = append(changes.Updated, ".clinerules")
		} else {
			changes.Skipped = append(changes.Skipped, ".clinerules")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the rules file
func (c *ClineAdapter) GetRulesPath() string {
	return ".clinerules"
}
