// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// ContinueAdapter handles Continue extension for VS Code.
// Continue uses a .continue/ folder with config.json and optional rules files.
// https://continue.dev/
type ContinueAdapter struct{}

// Name returns the adapter name
func (c *ContinueAdapter) Name() string {
	return "Continue"
}

// Detect checks if this is a Continue project.
// Look for .continue/ folder or .continuerules file.
func (c *ContinueAdapter) Detect(projectPath string) bool {
	continueDir := filepath.Join(projectPath, ".continue")
	if info, err := os.Stat(continueDir); err == nil && info.IsDir() {
		return true
	}
	rulesFile := filepath.Join(projectPath, ".continuerules")
	if _, err := os.Stat(rulesFile); err == nil {
		return true
	}
	return false
}

// Install creates Continue configuration from templates.
//
// Continue supports:
// - .continue/config.json - main configuration
// - .continue/prompts/ - custom slash commands
// - .continuerules - project-specific rules (like .cursorrules)
func (c *ContinueAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	continueDir := filepath.Join(opts.TargetDir, ".continue")
	rulesFile := filepath.Join(opts.TargetDir, ".continuerules")

	// Check if exists and not forcing
	if _, err := os.Stat(continueDir); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("continue config %s already exists (use --force to overwrite)", continueDir)
	}

	if opts.DryRun {
		return nil
	}

	// Create .continue directory
	if err := os.MkdirAll(filepath.Join(continueDir, "prompts"), 0755); err != nil {
		return err
	}

	// Create .continuerules file (similar to .cursorrules)
	content := c.buildRulesContent(tmpl)
	if err := os.WriteFile(rulesFile, []byte(content), 0644); err != nil {
		return err
	}

	// Create config.json with AGEN context
	configContent := c.buildConfigContent()
	return os.WriteFile(filepath.Join(continueDir, "config.json"), []byte(configContent), 0644)
}

// buildRulesContent creates the .continuerules content
func (c *ContinueAdapter) buildRulesContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Continue Rules - Generated by AGEN\n\n")
	sb.WriteString("> This file was generated by AGEN (AI Agent Template Manager)\n")
	sb.WriteString("> https://github.com/eshanized/agen\n\n")
	sb.WriteString("---\n\n")

	// Global rules
	sb.WriteString("## Code Standards\n\n")
	sb.WriteString("- Follow clean code principles (SRP, DRY, KISS)\n")
	sb.WriteString("- Use meaningful names that reveal intent\n")
	sb.WriteString("- Keep functions small and focused\n")
	sb.WriteString("- Write self-documenting code\n\n")

	// Agents
	sb.WriteString("## Available Agents\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills
	sb.WriteString("## Skills\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows
	sb.WriteString("## Slash Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// buildConfigContent creates Continue config.json
func (c *ContinueAdapter) buildConfigContent() string {
	return `{
  "$schema": "https://continue.dev/config-schema.json",
  "models": [],
  "customCommands": [],
  "contextProviders": [
    {
      "name": "codebase",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    }
  ],
  "slashCommands": [],
  "docs": []
}
`
}

// Update updates Continue configuration
func (c *ContinueAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	rulesFile := filepath.Join(opts.TargetDir, ".continuerules")

	if _, err := os.Stat(rulesFile); os.IsNotExist(err) {
		if err := c.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".continuerules", ".continue/config.json")
	} else {
		if opts.Force || opts.DryRun {
			content := c.buildRulesContent(tmpl)
			if !opts.DryRun {
				if err := os.WriteFile(rulesFile, []byte(content), 0644); err != nil {
					return nil, err
				}
			}
			changes.Updated = append(changes.Updated, ".continuerules")
		} else {
			changes.Skipped = append(changes.Skipped, ".continuerules")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the rules file
func (c *ContinueAdapter) GetRulesPath() string {
	return ".continuerules"
}
