// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// CopilotWorkspaceAdapter handles GitHub Copilot Workspace.
// Copilot Workspace uses .github/copilot-instructions.md for project context.
// https://docs.github.com/en/copilot/customizing-copilot
type CopilotWorkspaceAdapter struct{}

// Name returns the adapter name
func (c *CopilotWorkspaceAdapter) Name() string {
	return "CopilotWorkspace"
}

// Detect checks if this is a GitHub Copilot Workspace project.
// Look for .github/copilot-instructions.md file.
func (c *CopilotWorkspaceAdapter) Detect(projectPath string) bool {
	instructionsFile := filepath.Join(projectPath, ".github", "copilot-instructions.md")
	if _, err := os.Stat(instructionsFile); err == nil {
		return true
	}
	return false
}

// Install creates Copilot Workspace configuration from templates.
func (c *CopilotWorkspaceAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	githubDir := filepath.Join(opts.TargetDir, ".github")
	instructionsFile := filepath.Join(githubDir, "copilot-instructions.md")

	if _, err := os.Stat(instructionsFile); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("copilot instructions %s already exists (use --force to overwrite)", instructionsFile)
	}

	if opts.DryRun {
		return nil
	}

	// Create .github directory if it doesn't exist
	if err := os.MkdirAll(githubDir, 0755); err != nil {
		return err
	}

	content := c.buildContent(tmpl)
	return os.WriteFile(instructionsFile, []byte(content), 0644)
}

// buildContent creates the copilot-instructions.md content
func (c *CopilotWorkspaceAdapter) buildContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Copilot Instructions - Generated by AGEN\n\n")
	sb.WriteString("> Custom instructions for GitHub Copilot in this repository.\n")
	sb.WriteString("> Generated by AGEN (https://github.com/eshanized/agen)\n\n")
	sb.WriteString("---\n\n")

	// Project context
	sb.WriteString("## Project Context\n\n")
	sb.WriteString("This is an AGEN-managed project. Follow these guidelines when generating code.\n\n")

	// Code standards
	sb.WriteString("## Code Standards\n\n")
	sb.WriteString("When generating code for this project:\n\n")
	sb.WriteString("- Follow clean code principles (SRP, DRY, KISS)\n")
	sb.WriteString("- Use meaningful, descriptive names\n")
	sb.WriteString("- Keep functions small and focused\n")
	sb.WriteString("- Include appropriate error handling\n")
	sb.WriteString("- Write tests alongside new code\n")
	sb.WriteString("- Add comments for complex logic only\n\n")

	// Agents as personas
	sb.WriteString("## Available Personas\n\n")
	sb.WriteString("When asked, you can adopt these specialized personas:\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills as capabilities
	sb.WriteString("## Technical Capabilities\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows as commands
	sb.WriteString("## Workflow Commands\n\n")
	sb.WriteString("These slash commands trigger specific workflows:\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// Update updates Copilot Workspace configuration
func (c *CopilotWorkspaceAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	instructionsFile := filepath.Join(opts.TargetDir, ".github", "copilot-instructions.md")

	if _, err := os.Stat(instructionsFile); os.IsNotExist(err) {
		if err := c.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".github/copilot-instructions.md")
	} else {
		if opts.Force || opts.DryRun {
			if err := c.Install(tmpl, InstallOptions{
				TargetDir: opts.TargetDir,
				DryRun:    opts.DryRun,
				Force:     true,
			}); err != nil {
				return nil, err
			}
			changes.Updated = append(changes.Updated, ".github/copilot-instructions.md")
		} else {
			changes.Skipped = append(changes.Skipped, ".github/copilot-instructions.md")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the instructions file
func (c *CopilotWorkspaceAdapter) GetRulesPath() string {
	return ".github/copilot-instructions.md"
}
