// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// CursorAdapter handles Cursor IDE format.
// Cursor uses a single .cursorrules file in the project root.
// We need to convert our multi-file format into one consolidated file.
type CursorAdapter struct{}

// Name returns the adapter name
func (c *CursorAdapter) Name() string {
	return "Cursor"
}

// Detect checks if this is a Cursor project.
// look for .cursorrules file in project root.
func (c *CursorAdapter) Detect(projectPath string) bool {
	rulesFile := filepath.Join(projectPath, ".cursorrules")
	if _, err := os.Stat(rulesFile); err == nil {
		return true
	}
	return false
}

// Install creates the .cursorrules file from templates.
//
// How it works:
// 1. Load all agent rules and skills
// 2. Consolidate into a single markdown document
// 3. Write to .cursorrules file
//
// Why consolidate? Cursor only reads one file, so we need to merge
// everything that would normally be in .agent/ into one file.
// We include the most important rules and skip verbose documentation.
func (c *CursorAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	rulesFile := filepath.Join(opts.TargetDir, ".cursorrules")

	// check if exists and not forcing
	if _, err := os.Stat(rulesFile); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("cursor rules file %s already exists (use --force to overwrite)", rulesFile)
	}

	// Build consolidated rules content
	content := c.buildRulesContent(tmpl)

	if opts.DryRun {
		return nil
	}

	return os.WriteFile(rulesFile, []byte(content), 0644)
}

// buildRulesContent creates the consolidated .cursorrules content.
//
// Structure of the generated file:
// 1. Header with AGEN info
// 2. Global rules (from GEMINI.md equivalent)
// 3. Agent summaries (condensed)
// 4. Key skill references
// 5. Workflow command list
//
// We keep it concise because Cursor has context limits.
func (c *CursorAdapter) buildRulesContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Cursor Rules - Generated by AGEN\n\n")
	sb.WriteString("> This file was generated by AGEN (AI Agent Template Manager)\n")
	sb.WriteString("> https://github.com/eshanized/agen\n\n")
	sb.WriteString("---\n\n")

	// Global rules section
	sb.WriteString("## Global Rules\n\n")
	sb.WriteString("### Code Quality\n")
	sb.WriteString("- Follow clean code principles (SRP, DRY, KISS)\n")
	sb.WriteString("- Use meaningful names that reveal intent\n")
	sb.WriteString("- Keep functions small (max 20 lines)\n")
	sb.WriteString("- Write self-documenting code\n\n")

	// Agent summaries
	sb.WriteString("## Available Agents\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skill list (just names and descriptions)
	sb.WriteString("## Skills\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflow commands
	sb.WriteString("## Workflow Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// Update updates the .cursorrules file
func (c *CursorAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}

	rulesFile := filepath.Join(opts.TargetDir, ".cursorrules")

	// check if exists
	if _, err := os.Stat(rulesFile); os.IsNotExist(err) {
		// File doesn't exist, treat as new install
		if err := c.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".cursorrules")
	} else {
		// File exists, update it
		if opts.Force || opts.DryRun {
			if err := c.Install(tmpl, InstallOptions{
				TargetDir: opts.TargetDir,
				DryRun:    opts.DryRun,
				Force:     true,
			}); err != nil {
				return nil, err
			}
			changes.Updated = append(changes.Updated, ".cursorrules")
		} else {
			// User might have modified, skip
			changes.Skipped = append(changes.Skipped, ".cursorrules")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the rules file
func (c *CursorAdapter) GetRulesPath() string {
	return ".cursorrules"
}
