// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// EmacsAdapter handles Emacs configurations for AI plugins.
// Supports:
// - gptel
// - ellama
// - copilot.el
type EmacsAdapter struct{}

// Name returns the adapter name
func (e *EmacsAdapter) Name() string {
	return "Emacs"
}

// Detect checks if this is an Emacs-managed project.
// Look for .dir-locals.el or .emacs-project.
func (e *EmacsAdapter) Detect(projectPath string) bool {
	dirLocals := filepath.Join(projectPath, ".dir-locals.el")
	if _, err := os.Stat(dirLocals); err == nil {
		return true
	}
	emacsDir := filepath.Join(projectPath, ".emacs.d")
	if info, err := os.Stat(emacsDir); err == nil && info.IsDir() {
		return true
	}
	return false
}

// Install creates Emacs AI configuration from templates.
func (e *EmacsAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	emacsDir := filepath.Join(opts.TargetDir, ".emacs-project")
	rulesFile := filepath.Join(emacsDir, "ai-context.md")

	if _, err := os.Stat(emacsDir); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("emacs config %s already exists (use --force to overwrite)", emacsDir)
	}

	if opts.DryRun {
		return nil
	}

	// Create .emacs-project directory
	if err := os.MkdirAll(emacsDir, 0755); err != nil {
		return err
	}

	// Create ai-context.md
	rulesContent := e.buildRulesContent(tmpl)
	if err := os.WriteFile(rulesFile, []byte(rulesContent), 0644); err != nil {
		return err
	}

	// Create .dir-locals.el
	dirLocalsContent := e.buildDirLocals()
	dirLocalsFile := filepath.Join(opts.TargetDir, ".dir-locals.el")
	return os.WriteFile(dirLocalsFile, []byte(dirLocalsContent), 0644)
}

// buildRulesContent creates the AI context content
func (e *EmacsAdapter) buildRulesContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Emacs AI Context - Generated by AGEN\n\n")
	sb.WriteString("> This file provides context for Emacs AI plugins (gptel, ellama).\n")
	sb.WriteString("> Generated by AGEN (https://github.com/eshanized/agen)\n\n")
	sb.WriteString("---\n\n")

	// Code standards
	sb.WriteString("## Coding Standards\n\n")
	sb.WriteString("- Follow clean code principles\n")
	sb.WriteString("- Use meaningful names\n")
	sb.WriteString("- Keep functions focused\n")
	sb.WriteString("- Write comprehensive tests\n\n")

	// Agents
	sb.WriteString("## Available Agents\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills
	sb.WriteString("## Skills\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows
	sb.WriteString("## Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// buildDirLocals creates .dir-locals.el
func (e *EmacsAdapter) buildDirLocals() string {
	return `;;; .dir-locals.el --- Project-local Emacs config (Generated by AGEN)

((nil . ((eval . (progn
                   ;; Set project AI context file
                   (setq-local gptel-context-file ".emacs-project/ai-context.md")
                   ;; For ellama
                   (setq-local ellama-context-file ".emacs-project/ai-context.md")))
         (indent-tabs-mode . nil)
         (tab-width . 2))))

;;; .dir-locals.el ends here
`
}

// Update updates Emacs configuration
func (e *EmacsAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	rulesFile := filepath.Join(opts.TargetDir, ".emacs-project", "ai-context.md")

	if _, err := os.Stat(rulesFile); os.IsNotExist(err) {
		if err := e.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".emacs-project/ai-context.md", ".dir-locals.el")
	} else {
		if opts.Force || opts.DryRun {
			rulesContent := e.buildRulesContent(tmpl)
			if !opts.DryRun {
				if err := os.WriteFile(rulesFile, []byte(rulesContent), 0644); err != nil {
					return nil, err
				}
			}
			changes.Updated = append(changes.Updated, ".emacs-project/ai-context.md")
		} else {
			changes.Skipped = append(changes.Skipped, ".emacs-project/ai-context.md")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the rules file
func (e *EmacsAdapter) GetRulesPath() string {
	return ".emacs-project/ai-context.md"
}
