// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eshan Roy <eshanized@proton.me>
//
// AGEN - AI Agent Template Manager
// A cross-platform CLI tool for managing AI agent templates

package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshanized/agen/internal/templates"
)

// JetBrainsAdapter handles JetBrains IDEs (IntelliJ, PyCharm, WebStorm, etc.).
// JetBrains uses .idea/ folder for project settings.
// AI Assistant settings can be configured via project-level inspection profiles.
type JetBrainsAdapter struct{}

// Name returns the adapter name
func (j *JetBrainsAdapter) Name() string {
	return "JetBrains"
}

// Detect checks if this is a JetBrains project.
// Look for .idea/ folder.
func (j *JetBrainsAdapter) Detect(projectPath string) bool {
	ideaDir := filepath.Join(projectPath, ".idea")
	if info, err := os.Stat(ideaDir); err == nil && info.IsDir() {
		return true
	}
	return false
}

// Install creates JetBrains AI configuration from templates.
//
// JetBrains AI Assistant can read:
// - .idea/ai-assistant.xml - AI settings
// - Project-level markdown files that get indexed
func (j *JetBrainsAdapter) Install(tmpl *templates.Templates, opts InstallOptions) error {
	ideaDir := filepath.Join(opts.TargetDir, ".idea")
	aiConfigFile := filepath.Join(ideaDir, "ai-assistant.xml")
	rulesFile := filepath.Join(opts.TargetDir, ".jbrules.md")

	if _, err := os.Stat(aiConfigFile); err == nil && !opts.Force {
		if opts.DryRun {
			return nil
		}
		return fmt.Errorf("jetbrains AI config %s already exists (use --force to overwrite)", aiConfigFile)
	}

	if opts.DryRun {
		return nil
	}

	// Create .idea directory if it doesn't exist
	if err := os.MkdirAll(ideaDir, 0755); err != nil {
		return err
	}

	// Create ai-assistant.xml
	aiConfig := j.buildAIConfig()
	if err := os.WriteFile(aiConfigFile, []byte(aiConfig), 0644); err != nil {
		return err
	}

	// Create .jbrules.md for context (gets indexed by JetBrains)
	rulesContent := j.buildRulesContent(tmpl)
	return os.WriteFile(rulesFile, []byte(rulesContent), 0644)
}

// buildAIConfig creates JetBrains AI Assistant configuration
func (j *JetBrainsAdapter) buildAIConfig() string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="AIAssistantSettings">
    <option name="enableCodeCompletion" value="true" />
    <option name="enableChatAssistant" value="true" />
    <option name="contextAwareness" value="PROJECT" />
  </component>
</project>
`
}

// buildRulesContent creates the .jbrules.md content
func (j *JetBrainsAdapter) buildRulesContent(tmpl *templates.Templates) string {
	var sb strings.Builder

	sb.WriteString("# Project Rules - Generated by AGEN\n\n")
	sb.WriteString("> This file provides context for JetBrains AI Assistant.\n")
	sb.WriteString("> Generated by AGEN (https://github.com/eshanized/agen)\n\n")
	sb.WriteString("---\n\n")

	// Code standards
	sb.WriteString("## Code Standards\n\n")
	sb.WriteString("- Follow clean code principles\n")
	sb.WriteString("- Use meaningful names that reveal intent\n")
	sb.WriteString("- Keep functions focused and small\n")
	sb.WriteString("- Write comprehensive tests\n")
	sb.WriteString("- Document public APIs\n\n")

	// Agents
	sb.WriteString("## Development Roles\n\n")
	for name, agent := range tmpl.Agents {
		sb.WriteString("### ")
		sb.WriteString(name)
		sb.WriteString("\n")
		sb.WriteString(agent.Description)
		sb.WriteString("\n\n")
	}

	// Skills
	sb.WriteString("## Technical Skills\n\n")
	for name, skill := range tmpl.Skills {
		sb.WriteString("- **")
		sb.WriteString(name)
		sb.WriteString("**: ")
		sb.WriteString(skill.Description)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Workflows
	sb.WriteString("## Workflow Commands\n\n")
	for name, workflow := range tmpl.Workflows {
		displayName := name
		if !strings.HasPrefix(name, "/") {
			displayName = "/" + name
		}
		sb.WriteString("- `")
		sb.WriteString(displayName)
		sb.WriteString("`: ")
		sb.WriteString(workflow.Description)
		sb.WriteString("\n")
	}

	return sb.String()
}

// Update updates JetBrains configuration
func (j *JetBrainsAdapter) Update(tmpl *templates.Templates, opts UpdateOptions) (*UpdateChanges, error) {
	changes := &UpdateChanges{}
	rulesFile := filepath.Join(opts.TargetDir, ".jbrules.md")

	if _, err := os.Stat(rulesFile); os.IsNotExist(err) {
		if err := j.Install(tmpl, InstallOptions{
			TargetDir: opts.TargetDir,
			DryRun:    opts.DryRun,
			Force:     true,
		}); err != nil {
			return nil, err
		}
		changes.Added = append(changes.Added, ".jbrules.md", ".idea/ai-assistant.xml")
	} else {
		if opts.Force || opts.DryRun {
			rulesContent := j.buildRulesContent(tmpl)
			if !opts.DryRun {
				if err := os.WriteFile(rulesFile, []byte(rulesContent), 0644); err != nil {
					return nil, err
				}
			}
			changes.Updated = append(changes.Updated, ".jbrules.md")
		} else {
			changes.Skipped = append(changes.Skipped, ".jbrules.md")
		}
	}

	return changes, nil
}

// GetRulesPath returns the path to the rules file
func (j *JetBrainsAdapter) GetRulesPath() string {
	return ".jbrules.md"
}
